workflows:
  android-app:
    name: Android App
    instance_type: mac_mini_m1
    environment:
      java: 11
    scripts:
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Make Gradle wrapper executable
        script: chmod +x ./gradlew
      - name: Build Android app
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
